name: Deploy Mentis API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files with SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: "/var/www/html/mentis-api/"
          EXCLUDE: "/node_modules/, **.env, .env.local, .gitignore, .git/, .github/, .devops/, .vscode/"
          SCRIPT_BEFORE: |
            echo "===> Iniciando deploy"
            cd /var/www/html/mentis-api/
            .devops/halt.sh
          SCRIPT_AFTER: |
            echo "===> Deploy finalizado"
            cd /var/www/html/mentis-api/
            .devops/run.sh
